# Generated by Django 4.2.1 on 2023-06-06 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vending_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='category',
            field=models.CharField(default='unknown', max_length=100),
        ),
        migrations.AlterField(
            model_name='products',
            name='price',
            field=models.BooleanField(max_length=10, verbose_name='Price'),
        ),
    ]
