# Generated by Django 4.2.1 on 2023-06-06 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vending_app', '0003_alter_products_category_alter_products_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='img_link',
            field=models.CharField(default='unknown', max_length=255, verbose_name='Link'),
        ),
    ]
