# Generated by Django 4.2.1 on 2023-06-09 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vending_app', '0006_remove_cartitem_cart_remove_cartitem_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='added_to_cart',
            field=models.BooleanField(default=True, verbose_name='added_to_cart'),
        ),
    ]
