# Generated by Django 4.2.1 on 2023-06-09 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vending_app', '0009_alter_products_added_to_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='added_to_cart',
        ),
    ]
