# Generated by Django 4.2.1 on 2023-06-21 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vending_app', '0011_products_added_to_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='added_to_cart',
        ),
        migrations.AddField(
            model_name='products',
            name='total',
            field=models.IntegerField(default=0, verbose_name='Total'),
        ),
    ]
